apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: test-ingress
spec:
  rules:
  - host: est.current-time.io
    http:
      paths:
      - path: /
        backend:
          serviceName: est-current-time-service
          servicePort: 8083
  - host: pst.current-time.io
    http:
      paths:
      - path: /
        backend:
          serviceName: pst-current-time-service
          servicePort: 8083
  - host: utc.current-time.io
    http:
      paths:
      - path: /
        backend:
          serviceName: utc-current-time-service
          servicePort: 8083